export const INCIDENT_LEGAL = "INCIDENT_LEGAL"
export const INCIDENT_LEGAL_RESPPONSE = "INCIDENT_LEGAL_RESPPONSE"
export const INCIDENT_REINTEGRATION="INCIDENT_REINTEGRATION"
export const INCIDENT_REINTEGRATION_RESPPONSE = "INCIDENT_REINTEGRATION_RESPPONSE"


