export const INCIDENT_LEGAL = "INCIDENT_LEGAL"
export const INCIDENT_LEGAL_RESPPONSE = "INCIDENT_LEGAL_RESPPONSE"
export const INCIDENT_REINTEGRATION="INCIDENT_REINTEGRATION"
export const INCIDENT_REINTEGRATION_RESPPONSE = "INCIDENT_REINTEGRATION_RESPPONSE"
export const INCIDENT_MHPSS="INCIDENT_MHPSS"
export const INCIDENT_MHPSS_RESPPONSE="INCIDENT_MHPSS_RESPPONSE"
export const GET_ALL_CASE="GET_ALL_CASE"
export const GET_ALL_CASE_RESPONSE="GET_ALL_CASE_RESPONSE"


